services:
 postgres:
  image: postgres:16
  environment:
   POSTGRES_DB: crm
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
   - "5432:5432"

 api:
  image: node:20
  working_dir: /app
  volumes:
   - ./backend:/app
  command: npm start
  ports:
   - "3000:3000"
  depends_on:
   - postgres